apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gravity-report-exporter-pvc 
  namespace: gravity-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  #storageClassName: standard
  #storageClassName: spare

---

apiVersion: "gravity.brobridge.com/v3"
kind: "Exporter"
metadata:
  name: "gravity-report-exporter"
  namespace: gravity-demo
spec:
  type: stan
  #image: brobridgehub/gravity-exporter-stan:v2.2.0
  #initImage: busybox:1.28  
  imagePullPolicy: Always
  config:
    gravityHost: gravity-report-nats:4222
    subscriptionSettings: |
      {
        "subscriptions": {
          "GfactorProduct": [
            "rowData.source.SendProduct"
            "rowData.source.SendRecordProduct"
            "rowData.source.SendRecordRecordProduct"
          ]

        }
      }

    stanConfig:
      host: gravity-report-nats:4222
      clusterID: external-stan
    volume:
      name: gravity-report-exporter-store
      persistentVolumeClaim:
        claimName: gravity-report-exporter-pvc

