apiVersion: apps/v1
kind: Deployment
metadata:
  name: gravity-atomic-git-rep-p1
  labels:
    app: gravity-atomic-git-rep-p1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gravity-atomic-git-rep-p1
  template:
    metadata:
      labels:
        app: gravity-atomic-git-rep-p1
    spec:
      containers:
        - name: gravity-atomic-git-rep-p1
          image: pascalgn/gravity-atomic-git-rep-p1-docker:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gravity-atomic-git-rep-p1
  labels:
    app: gravity-atomic-git-rep-p1
spec:
  type: NodePort
  ports:
    - port: 3000
  selector:
    app: gravity-atomic-git-rep-p1
