apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gravity1-atomic-pvc 
  namespace: gravity-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  #storageClassName: wcppolicy
  #storageClassName: spare 

---

apiVersion: "atomic.brobridge.com/v1"
kind: "Atomic"
metadata:
  name: "gravity1-db-api"
  namespace: gravity-demo
spec:
  #replicas: 1
  #gitImage: alpine/git:v2.32.0
  #atomicImage: brobridgehub/atomic:v0.0.5
  #imagePullPolicy: IfNotPresent
  ports: 1880
  config:
    #gitHttpUrl: http://demo:281a8506839ae8246b6eac80065aab94d4c2ea2d@gitea:3000/demo/flow1.git
    gitHttpUrl: https://kenduest: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@github.com/kenduest/test-flow1
    gitBranch: main
    enableEditor: true
    volume:
      name: atomic-store
      persistentVolumeClaim:
        claimName: gravity1-atomic-pvc
    service:
      serviceType: LoadBalancer
