apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gravity1-source-controller-pvc 
  namespace: gravity-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  #storageClassName: spare
  #storageClassName: wcppolicy

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gravity1-source-synchronizer-pvc 
  namespace: gravity-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  #storageClassName: spare
  #storageClassName: wcppolicy

---

apiVersion: "gravity.brobridge.com/v4"
kind: "Gravity"
metadata:
  name: "gravity1"
  namespace: gravity-demo
spec:

  initSpec:

  natsSpec:
    replicas: 3

  controllerSpec:
    config:
      volume:
        name: gravity1-source-controller-store
        persistentVolumeClaim:
          claimName: gravity1-source-controller-pvc

  synchronizerSpec:
    imagePullPolicy: NotIfPresent
    config:
      collectionSettings: |
        {
          "collections": {
            "DeliveryPool": {
              "schema": {
                 "UID": { "type": "string" }, 
                 "SerialNum": { "type": "uint" },
                 "MPhoneNum": { "type": "string" }, 
                 "MsgData": { "type": "string" },
                 "Priority": { "type": "uint" },
                 "BookingTime": { "type": "time" }, 
                 "ExpireTime": { "type": "uint" },
                 "DepID": { "type": "string" },
                 "MsgType": { "type": "string" },
                 "Memo": { "type": "string" },
                 "SenderID": { "type": "string" },
                 "Bu": { "type": "string" },
                 "Company": { "type": "string" },
                 "Channel": { "type": "string" },
                 "Reference": { "type": "string" },
                 "GroupID": { "type": "string" },
                 "ObjectID": { "type": "string" }
              }
            }
            }
          }
        }

      rulesSettings: |
        {
          "rules": [
            {
              "event": "DeliveryPoolInitialize",
              "collection": "DeliveryPool",
              "method": "insert",
              "primaryKey": "UID",
              "schema": {
                 "UID": { "type": "string" },
                 "SerialNum": { "type": "uint" },
                 "MPhoneNum": { "type": "string" },
                 "MsgData": { "type": "string" },
                 "Priority": { "type": "uint" },
                 "BookingTime": { "type": "time" },
                 "ExpireTime": { "type": "uint" },
                 "DepID": { "type": "string" },
                 "MsgType": { "type": "string" },
                 "Memo": { "type": "string" },
                 "SenderID": { "type": "string" },
                 "Bu": { "type": "string" },
                 "Company": { "type": "string" },
                 "Channel": { "type": "string" },
                 "Reference": { "type": "string" },
                 "GroupID": { "type": "string" },
                 "ObjectID": { "type": "string" }
               },
              "handler": {
                "script": "
                  return {
                    UID: source.UID,
                    SerialNum: source.SerialNum,
                    MPhoneNum: source.MPhoneNum,
                    MsgData: source.MsgData,
                    Priority: source.Priority,
                    BookingTime: source.BookingTime,
                    ExpireTime: source.ExpireTime,
                    DepID: source.DepID,
                    MsgType: source.MsgType,
                    Memo: source.Memo,
                    SenderID: source.SenderID,
                    Bu: source.Bu,
                    Company: source.Company,
                    Channel: source.Channel,
                    Reference: source.Reference,
                    GroupID: source.GroupID,
                    ObjectID: source.ObjectID
                  }"
              }
            },

            {
              "event": "DeliveryPoolCreate",
              "collection": "DeliveryPool",
              "method": "insert",
              "primaryKey": "UID",
              "schema": {
                 "UID": { "type": "string" },
                 "SerialNum": { "type": "uint" },
                 "MPhoneNum": { "type": "string" },
                 "MsgData": { "type": "string" },
                 "Priority": { "type": "uint" },
                 "BookingTime": { "type": "time" },
                 "ExpireTime": { "type": "uint" },
                 "DepID": { "type": "string" },
                 "MsgType": { "type": "string" },
                 "Memo": { "type": "string" },
                 "SenderID": { "type": "string" },
                 "Bu": { "type": "string" },
                 "Company": { "type": "string" },
                 "Channel": { "type": "string" },
                 "Reference": { "type": "string" },
                 "GroupID": { "type": "string" },
                 "ObjectID": { "type": "string" }
               },
              "handler": {
                "script": "
                  return {
                    UID: source.UID,
                    SerialNum: source.SerialNum,
                    MPhoneNum: source.MPhoneNum,
                    MsgData: source.MsgData,
                    Priority: source.Priority,
                    BookingTime: source.BookingTime,
                    ExpireTime: source.ExpireTime,
                    DepID: source.DepID,
                    MsgType: source.MsgType,
                    Memo: source.Memo,
                    SenderID: source.SenderID,
                    Bu: source.Bu,
                    Company: source.Company,
                    Channel: source.Channel,
                    Reference: source.Reference,
                    GroupID: source.GroupID,
                    ObjectID: source.ObjectID
                  }"
              }
            },

            {
              "event": "DeliveryPoolUpdate",
              "collection": "DeliveryPool",
              "method": "update",
              "primaryKey": "UID",
              "schema": {
                 "UID": { "type": "string" },
                 "SerialNum": { "type": "uint" },
                 "MPhoneNum": { "type": "string" },
                 "MsgData": { "type": "string" },
                 "Priority": { "type": "uint" },
                 "BookingTime": { "type": "time" },
                 "ExpireTime": { "type": "uint" },
                 "DepID": { "type": "string" },
                 "MsgType": { "type": "string" },
                 "Memo": { "type": "string" },
                 "SenderID": { "type": "string" },
                 "Bu": { "type": "string" },
                 "Company": { "type": "string" },
                 "Channel": { "type": "string" },
                 "Reference": { "type": "string" },
                 "GroupID": { "type": "string" },
                 "ObjectID": { "type": "string" }
               },

              "handler": {
                "script": "
                  return {
                    UID: source.UID,
                    SerialNum: source.SerialNum,
                    MPhoneNum: source.MPhoneNum,
                    MsgData: source.MsgData,
                    Priority: source.Priority,
                    BookingTime: source.BookingTime,
                    ExpireTime: source.ExpireTime,
                    DepID: source.DepID,
                    MsgType: source.MsgType,
                    Memo: source.Memo,
                    SenderID: source.SenderID,
                    Bu: source.Bu,
                    Company: source.Company,
                    Channel: source.Channel,
                    Reference: source.Reference,
                    GroupID: source.GroupID,
                    ObjectID: source.ObjectID
                  }"
              }
            },
            {
              "event": "DeliveryPoolDelete",
              "collection": "DeliveryPool",
              "method": "delete",
              "primaryKey": "UID",
              "schema": {
                 "UID": { "type": "string" },
                 "SerialNum": { "type": "uint" },
                 "MPhoneNum": { "type": "string" },
                 "MsgData": { "type": "string" },
                 "Priority": { "type": "uint" },
                 "BookingTime": { "type": "time" },
                 "ExpireTime": { "type": "uint" },
                 "DepID": { "type": "string" },
                 "MsgType": { "type": "string" },
                 "Memo": { "type": "string" },
                 "SenderID": { "type": "string" },
                 "Bu": { "type": "string" },
                 "Company": { "type": "string" },
                 "Channel": { "type": "string" },
                 "Reference": { "type": "string" },
                 "GroupID": { "type": "string" },
                 "ObjectID": { "type": "string" }
               },
              "handler": {
                "script": "
                  return {
                    UID: source.UID,
                    SerialNum: source.SerialNum,
                    MPhoneNum: source.MPhoneNum,
                    MsgData: source.MsgData,
                    Priority: source.Priority,
                    BookingTime: source.BookingTime,
                    ExpireTime: source.ExpireTime,
                    DepID: source.DepID,
                    MsgType: source.MsgType,
                    Memo: source.Memo,
                    SenderID: source.SenderID,
                    Bu: source.Bu,
                    Company: source.Company,
                    Channel: source.Channel,
                    Reference: source.Reference,
                    GroupID: source.GroupID,
                    ObjectID: source.ObjectID
                  }"
              }
            }
          ]
        }

      volume:
        name: gravity1-source-synchronizer-store
        persistentVolumeClaim:
          claimName: gravity1-source-synchronizer-pvc

