apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gravity2-source-controller-pvc 
  namespace: gravity-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  #storageClassName: spare
  #storageClassName: wcppolicy

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gravity2-source-synchronizer-pvc 
  namespace: gravity-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  #storageClassName: spare
  #storageClassName: wcppolicy

---

apiVersion: "gravity.brobridge.com/v4"
kind: "Gravity"
metadata:
  name: "gravity2"
  namespace: gravity-demo
spec:
  natsSpec:
    replicas: 3

  controllerSpec:
    config:
      volume:
        name: gravity2-source-controller-store
        persistentVolumeClaim:
          claimName: gravity2-source-controller-pvc

  synchronizerSpec:
    imagePullPolicy: NotIfPresent
    config:
      collectionSettings: |
        {
          "collections": {
            "DeliveryPool": {
              "schema": {
                 "UID": { "type": "string" }, 
                 "SerialNum": { "type": "uint" },
                 "MPhoneNum": { "type": "string" }, 
                 "MsgData": { "type": "string" },
                 "Priority": { "type": "uint" },
                 "BookingTime": { "type": "time" }, 
                 "ExpireTime": { "type": "uint" },
                 "DepID": { "type": "string" },
                 "MsgType": { "type": "string" },
                 "Memo": { "type": "string" },
                 "SenderID": { "type": "string" },
                 "Bu": { "type": "string" },
                 "Company": { "type": "string" },
                 "Channel": { "type": "string" },
                 "Reference": { "type": "string" },
                 "GroupID": { "type": "string" },
                 "ObjectID": { "type": "string" },
                 "BatchID": { "type": "string" }
              }
            }
            }
          }
        }

      rulesSettings: |
        {
          "rules": [
            {
              "event": "DeliveryPoolInitialize",
              "collection": "DeliveryPool",
              "method": "insert",
              "primaryKey": "UID",
              "schema": {
                 "UID": { "type": "string" }, 
                 "SerialNum": { "type": "uint" },
                 "SerialNum": { "type": "uint" },
                 "MPhoneNum": { "type": "string" },
                 "MsgData": { "type": "string" },
                 "Priority": { "type": "uint" },
                 "BookingTime": { "type": "time" },
                 "ExpireTime": { "type": "uint" },
                 "DepID": { "type": "string" },
                 "MsgType": { "type": "string" },
                 "Memo": { "type": "string" },
                 "SenderID": { "type": "string" },
                 "Bu": { "type": "string" },
                 "Company": { "type": "string" },
                 "Channel": { "type": "string" },
                 "Reference": { "type": "string" },
                 "GroupID": { "type": "string" },
                 "ObjectID": { "type": "string" },
                 "BatchID": { "type": "string" }
               },
              "handler": {
                "script": "return source"
              }
            },

            {
              "event": "DeliveryPoolCreate",
              "collection": "DeliveryPool",
              "method": "insert",
              "primaryKey": "UID",
              "schema": {
                 "UID": { "type": "string" }, 
                 "SerialNum": { "type": "uint" },
                 "MPhoneNum": { "type": "string" },
                 "MsgData": { "type": "string" },
                 "Priority": { "type": "uint" },
                 "BookingTime": { "type": "time" },
                 "ExpireTime": { "type": "uint" },
                 "DepID": { "type": "string" },
                 "MsgType": { "type": "string" },
                 "Memo": { "type": "string" },
                 "SenderID": { "type": "string" },
                 "Bu": { "type": "string" },
                 "Company": { "type": "string" },
                 "Channel": { "type": "string" },
                 "Reference": { "type": "string" },
                 "GroupID": { "type": "string" },
                 "ObjectID": { "type": "string" },
                 "BatchID": { "type": "string" }
               },
              "handler": {
                "script": "return source"
              }
            },

            {
              "event": "DeliveryPoolUpdate",
              "collection": "DeliveryPool",
              "method": "update",
              "primaryKey": "UID",
              "schema": {
                 "UID": { "type": "string" }, 
                 "SerialNum": { "type": "uint" },
                 "MPhoneNum": { "type": "string" },
                 "MsgData": { "type": "string" },
                 "Priority": { "type": "uint" },
                 "BookingTime": { "type": "time" },
                 "ExpireTime": { "type": "uint" },
                 "DepID": { "type": "string" },
                 "MsgType": { "type": "string" },
                 "Memo": { "type": "string" },
                 "SenderID": { "type": "string" },
                 "Bu": { "type": "string" },
                 "Company": { "type": "string" },
                 "Channel": { "type": "string" },
                 "Reference": { "type": "string" },
                 "GroupID": { "type": "string" },
                 "ObjectID": { "type": "string" },
                 "BatchID": { "type": "string" }
               },

              "handler": {
                "script": "return source"
              }
            },
            {
              "event": "DeliveryPoolDelete",
              "collection": "DeliveryPool",
              "method": "delete",
              "primaryKey": "UID",
              "schema": {
                 "UID": { "type": "string" }, 
                 "SerialNum": { "type": "uint" },
                 "MPhoneNum": { "type": "string" },
                 "MsgData": { "type": "string" },
                 "Priority": { "type": "uint" },
                 "BookingTime": { "type": "time" },
                 "ExpireTime": { "type": "uint" },
                 "DepID": { "type": "string" },
                 "MsgType": { "type": "string" },
                 "Memo": { "type": "string" },
                 "SenderID": { "type": "string" },
                 "Bu": { "type": "string" },
                 "Company": { "type": "string" },
                 "Channel": { "type": "string" },
                 "Reference": { "type": "string" },
                 "GroupID": { "type": "string" },
                 "ObjectID": { "type": "string" },
                 "BatchID": { "type": "string" }
               },
              "handler": {
                "script": "return source"
              }
            }
          ]
        }

      volume:
        name: gravity2-source-synchronizer-store
        persistentVolumeClaim:
          claimName: gravity2-source-synchronizer-pvc

