apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gravity2-demo-adapter-pvc 
  namespace: gravity-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  #storageClassName: wcppolicy
  #storageClassName: spare

---

apiVersion: "gravity.brobridge.com/v4"
kind: "Adapter"
metadata:
  name: "gravity2-adapter-source"
  namespace: gravity-demo
spec:
  type: mssql
  imagePullPolicy: IfNotPresent
  image: smssit.azurecr.io/gravity/gravity-adapter-mssql:v2.2.2
  #image: brobridgehub/gravity-adapter-mssql:v2.2.2
  config:
    gravityHost: gravity2-nats
    gravityPort: 4222
    storeEnabled: true
    sourceSettings: |
       {
            "sources": {
                    "mssql_source2-1": {
                            "disabled": false,
                            "host": "source-mssql2-1",
                            "port": 1433,
                            "username": "SA",
                            "password": "Br0bridge@mssql",
                            "dbname": "smsdb",
                            "param": "",
                            "initialLoad": true,
                            "interval": 2,
                            "tables": {
                                      "dbo.DeliveryPool":{
                                              "events": {
                                                      "snapshot": "DeliveryPoolInitialize",
                                                      "create": "DeliveryPoolCreate",
                                                      "update": "DeliveryPoolUpdate",
                                                      "delete": "DeliveryPoolDelete"
                                              }
                                      }
                            }
                    },

                    "mssql_source2-2": {
                            "disabled": false,
                            "host": "source-mssql2-2",
                            "port": 1433,
                            "username": "SA",
                            "password": "Br0bridge@mssql",
                            "dbname": "smsdb",
                            "param": "",
                            "initialLoad": true,
                            "interval": 2,
                            "tables": {
                                      "dbo.DeliveryPool":{
                                              "events": {
                                                      "snapshot": "DeliveryPoolInitialize",
                                                      "create": "DeliveryPoolCreate",
                                                      "update": "DeliveryPoolUpdate",
                                                      "delete": "DeliveryPoolDelete"
                                              }
                                      }
                            }
                    }
            }
       }

    volume:
      name: gravity2-demo-adapter-store
      persistentVolumeClaim:
        claimName: gravity2-demo-adapter-pvc
