apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-data-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  #storageClassName: standard
  #storageClassName: spare

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-config-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  #storageClassName: standard
  #storageClassName: spare

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:1.16.6-rootless
        ports:
        - containerPort: 3000
          name: gitea
        - containerPort: 22
          name: git-ssh
        volumeMounts:
        - mountPath: /var/lib/gitea
          name: git-data-volume
        - mountPath: /etc/gitea
          name: git-config-volume
      volumes:
      - name: git-data-volume
        persistentVolumeClaim:
          claimName: git-data-volume
      - name: git-config-volume
        persistentVolumeClaim:
          claimName: git-config-volume

---

apiVersion: v1
kind: Service
metadata:
  name: gitea
spec:
  ports:
  - name: client
    port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 31818
  selector:
    app: gitea
  type: LoadBalancer
