#!/usr/bin/env python3

import pymssql

hostname = '127.0.0.1:1433'
username = 'SA'
password = 'Br0bridge@mssql'
databases = ['TestDB' ]

for db in databases:
    conn = pymssql.connect(host=hostname, user=username, password=password, database=db)
    cursor = conn.cursor(as_dict=True)
    cursor.execute("DELETE from dbo.users")
    conn.commit() 
    cursor.close()
    conn.close()

hostname = '127.0.0.1:2433'
username = 'SA'
password = 'Br0bridge@mssql'
databases = ['TestDB2']

for db in databases:
    conn = pymssql.connect(host=hostname, user=username, password=password, database=db)
    cursor = conn.cursor(as_dict=True)
    cursor.execute("DELETE from dbo.users")
    conn.commit() 
    cursor.close()
    conn.close()

