#!/usr/bin/env python3

import pymssql

hostname = '127.0.0.1:1433'
username = 'SA'
password = 'Br0bridge@mssql'
database = 'TestDB'

conn = pymssql.connect(host=hostname, user=username, password=password, database=database)
cursor = conn.cursor(as_dict=True)
cursor.execute("SELECT * FROM dbo.users")

for index, row in enumerate(cursor):
    print("#%s\n%s\n" % (index+1,row))

cursor.close()
conn.close()

