#!/usr/bin/env python3

import pymssql
import sys 
from datetime import datetime

hostname = '127.0.0.1:1433'
username = 'SA'
password = 'Br0bridge@mssql'
database = 'TestDB'

sql_template="""INSERT INTO "dbo".users("id", "name", "disabled", "gender", "username", "email", "phone") Values ({id},'{name}', {disabled}, {gender}, '{username}', '{email}', '{phone}')"""

def gen_data(i):

    sql = sql_template.format(id=i, name='Peter%s' % i, gender=0, username='peter%s' % i, email="xxx@localhost", phone="12345", disabled=0)
    return sql

if len(sys.argv) == 1:
    print("\nUsage: write-db-delivery [start-index] [amount]\n ")
    sys.exit(1)

n1 = int(sys.argv[1])
n2 = int(sys.argv[2])

conn = pymssql.connect(host=hostname, user=username, password=password, database=database)
cursor = conn.cursor(as_dict=True)

for i in range(n1,n2):
    sql = gen_data(i)
    print("#%d %s\n" % (i,sql))
    ret = cursor.execute(sql);

conn.commit() 
conn.close()

