[
{

    "uid":                 { "type": "string" }, 
    "event_code":          { "type": "string" },
    "way_name":            { "type": "string" },
    "send_from":           { "type": "int" },
    "send_time":           { "type": "datetime" },
    "expire_time":         { "type": "datetime" },
    "template_code":       { "type": "string" },
    "template_max_length": { "type": "int" },
    "send_mode":           { "type": "string"},
    "limit_mode":          { "type": "int" },
    "mod_reply":           { "type": "int" }, 
    "status":              { "type": "int" },
    "priority":            { "type": "int" },
    "msg_type":            { "type": "string" },
    "req_department":      { "type": "string" },
    "req_bu":              { "type": "string" },
    "req_company":         { "type": "string" },
    "req_channel":         { "type": "string" },
    "req_object_id":       { "type": "string" },
    "req_batch_id":        { "type": "string" },
    "memo":                { "type": "string" },
    "create_time":         { "type": "time" },
    "create_user":         { "type": "string" },
    "update_time":         { "type": "time" },
    "update_user":         { "type": "string" },
    "completed_time":      { "type": "time" },
    "canceled_time":       { "type": "time" },
    "update_expired_time": { "type": "time" }
},
{
    "uid":                 { "type": "string" },
    "way_name":            { "type": "string" },
    "serial_number":       { "type": "int" },
    "send_time":           { "type": "time" },
    "expire_time":         { "type": "time" },
    "customer_id":         { "type": "string" },
    "customer_phone":      { "type": "string" },
    "customer_reference":  { "type": "string" },
    "req_group_id":        { "type": "string" },
    "req_uid":             { "type": "string" },
    "content":             { "type": "string" },
    "return_code":         { "type": "string" },
    "calc_section":        { "type": "int" },
    "sending_section":     { "type": "int" },
    "section":             { "type": "int" },
    "success_section":     { "type": "int" },
    "failure_section":     { "type": "int" },
    "section_status_list": { "type": "string" },
    "is_long":             { "type": "int" },
    "is_international":    { "type": "int" },
    "msg_id":              { "type": "string" },
    "actual_send_time":    { "type": "time" },
    "actual_send_phone":   { "type": "string" },
    "gateway_id":          { "type": "int" },
    "status":              { "type": "int" }, 
    "resp_code":           { "type": "string" },
    "gwrecvat":            { "type": "string" },
    "acceptat":            { "type": "string" },
    "sendat":              { "type": "string" },
    "finish_time":         { "type": "time" },
    "meta":                { "type": "string" },
    "create_time":         { "type": "time" },
    "update_time":         { "type": "time" },
    "deliver_time":        { "type": "time" },
    "dr_time":             { "type": "time" },
    "canceled_time":       { "type": "time" },
    "update_expired_time": { "type": "time" }
},

{
    "send_record_uid": { "type": "string" },
    "send_uid":        { "type": "string" },
    "way_name":        { "type": "string" },
    "send_time":       { "type": "time" },
    "status":          { "type": "int" },
    "priority":        { "type": "int" },
    "expire_time":     { "type": "time" },
    "phone":           { "type": "string" },
    "content":         { "type": "string" },
    "limit_mode":      { "type": "int" },
    "msg_type":        { "type": "string" },
    "req_department":  { "type": "string" },
    "req_channel":     { "type": "string" },
    "req_group_id":    { "type": "string" },
    "req_object_id":   { "type": "string" },
    "meta":            { "type": "string" },
    "create_time":     { "type": "time" }
},  
 
{   
    "send_record_uid": { "type": "string" },
    "send_uid":        { "type": "string" }, 
    "way_name":        { "type": "string" },
    "send_time":       { "type": "time" },
    "status":          { "type": "int" },
    "priority":        { "type": "int" },
    "expire_time":     { "type": "time" },
    "phone":           { "type": "string" },
    "content":         { "type": "string" },
    "limit_mode":      { "type": "int" },
    "msg_type":        { "type": "string" },
    "req_department":  { "type": "string" },
    "req_channel":     { "type": "string" },
    "req_group_id":    { "type": "string" },
    "req_object_id":   { "type": "string" },
    "meta":            { "type": "string" },
    "create_time":     { "type": "time" }
},  

{   
    "uid":                { "type": "string" },
    "send_record_uid":    { "type": "string" },
    "customer_id":        { "type": "string" },
    "customer_phone":     { "type": "string" },
    "customer_reference": { "type": "string" },
    "tx_date":            { "type": "string" },
    "tx_time":            { "type": "string" },
    "event_code":         { "type": "string" },
    "return_code":        { "type": "string" },
    "create_time":        { "type": "time" },
    "update_time":        { "type": "time" },
    "reply_content":      { "type": "string" },
    "reply_time":         { "type": "time" },
    "status":             { "type": "int" },
    "gateway_id":         { "type": "int" },
    "code":               { "type": "string" }
}

]
