{

    "uid": { "type": "string" }, 
    "event_code": { "type": "string" },
    "eway_name": { "type": "string" },
    "esend_from": { "type": "int" },
    "esend_time": { "type": "datetime" },
    "eexpire_time": { "type": "datetime" },
    "etemplate_code": { "type": "string" },
    "etemplate_max_length": { "type": "int" },
    "esend_mode": { "type": "string"},
    "elimit_mode": { "type": "int" },
    "emod_reply": { "type": "int" }, 
    "estatus" :{ "type": "int" },
    "epriority" :{ "type": "int" },
    "emsg_type" :{ "type": "string" },
    "ereq_department" :{ "type": "string" },
    "ereq_bu" :{ "type": "string" },
    "ereq_company":{ "type": "string" },
    "ereq_channel":{ "type": "string" },
    "ereq_object_id": { "type": "string" },
    "ereq_batch_id": { "type": "string" },
    "ememo":{ "type": "string" },
    "ecreate_time":{ "type": "time" },
    "ecreate_user": { "type": "string" },
    "eupdate_time": {"type": "time" },
    "eupdate_user": { "type": "string" },
    "ecompleted_time": { "type": "time" },
    "ecanceled_time": { "type": "time" },
    "eupdate_expired_time": { "type": "time" }
}
